export const LIST_RECOGNITION = "LIST_RECOGNITION";

export const LIST_RECOGNITION_API = "LIST_RECOGNITION_API";

export const LOGIN_API = "LOGIN_API";

export const LOGIN = "LOGIN";

export const CORE_VALUE_LIST = "CORE_VALUE_LIST";

export const CORE_VALUE_API = "CORE_VALUE_API";

export const RECOGNIZE_TO_API = "RECOGNIZE_TO_API";

export const RECOGNIZE_TO = "RECOGNIZE_TO";

export const ADD_RECOGNITION_API = "ADD_RECOGNITION_API";

export const ADD_RECOGNITION = "ADD_RECOGNITION";

export const LIST_USERS_API = "LIST_USERS_API";

export const LIST_USERS = "LIST_USERS";

export const GIVE_HI5_API = "GIVE_HI5_API";

export const GIVE_HI5 = "GIVE_HI5";

export const USER_PROFILE = "USER_PROFILE";

export const USER_PROFILE_API = "USER_PROFILE_API";

export const USER_PROFILE_POST_API = "USER_PROFILE_POST_API";

export const LOGOUT_API = "LOGOUT_API";

export const S3_SIGNED_URL_API = "S3_SIGNED_URL_API";

export const S3_SIGNED_URL = "S3_SIGNED_URL";

export const S3_SIGNED_URL_POST = "S3_SIGNED_URL_POST";

export const FILTER_RECOGNITION = "FILTER_RECOGNITION";

export const FILTER_RECOGNITION_API = "FILTER_RECOGNITION_API";

export const USER_PROFILE_UPDATE_RESPONSE = "USER_PROFILE_UPDATE_RESPONSE";

export const GIVE_HI5_POST_RESPONSE = "GIVE_HI5_POST_RESPONSE";

export const FILTER_STATUS = "FILTER_STATUS";
